[package]
name = "editor"
version = "0.1.0"
authors = ["sink666 <er.basilisk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.2.0"
argparse = "0.2.2"
